version: '2.2'
services:
  app:
    depends_on:
      - redis
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    restart: always